#PatternFinder.py -- Retrieve a stored object generated by FileParser, find data patterns in it

import FileReader
import sys
import pickle
import numpy as np
import pandas as pd

#main:
if len(sys.argv) == 1:
  print('         Usage: retrieve a stored object generated by FileParser, find data patterns in it\n\
         Example: python PatternFinder.py testDB\n\
           testDB: file that saves the object')
  sys.exit(0)


with open(sys.argv[1], 'rb') as f:
  reader = pickle.load(f)

print("File size:" + str(reader.fileSize) + " Read chunk size:" + str(reader.chunkSize))

dfFile = pd.DataFrame(pd.Series(reader.fileHash))
dfFile.rename(columns={0:'count'}, inplace=True)

#sort hash index count:
dfFile.sort_values(['count'], ascending=[False], inplace=True)

print(dfFile.head())
