#PatternFinder.py -- Retrieve a stored object generated by FileParser, find data patterns in it

import FileReader
import sys
import pickle
import numpy as np
import pandas as pd

#main:
if len(sys.argv) == 1:
  print('         Usage: retrieve a stored object generated by FileParser, find data patterns in it\n\
         Example: python PatternFinder.py testDB\n\
           testDB: file that saves the object')
  sys.exit(0)


with open(sys.argv[1], 'rb') as f:
  reader = pickle.load(f)

print("Read chunk size:" + str(reader.chunkSize))
